name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm install
      working-directory: ./node-app
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install ansible -y
        ansible-galaxy collection install -r ansible/requirements.yml
    - name: Run Ansible Playbook
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
        EMAIL: m.a.amini2011@gmail.com
      run: |
        ansible-playbook ansible/playbook.yml -e "CR_PAT=$CR_PAT EMAIL=$EMAIL"
    - name: Build and Push Docker image
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
      run: |
        docker buildx create --use
        docker buildx build --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache -t ghcr.io/4min4m/node-app:latest ./node-app --push
        echo $CR_PAT | docker login ghcr.io -u 4min4m --password-stdin
    - name: Deploy to Kubernetes
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve